name: Docker Image CI Latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
      with:
        platforms: arm,arm64,amd64
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
    - name: Build the Docker image
      run: docker buildx build . --file Dockerfile --pull -t kcapp/frontend:latest --platform=linux/arm,linux/arm64,linux/amd64 --push
